### ISSUE TITLE
Extensions not supported in TypeScript

### ISSUE THREAD

**Issue by jamesobrooks** [siren-js/core#6]
Consider the following creation of an `Action` in a typescript project. The inclusion of additional properties results in a typescript error.

```ts
new Siren.Action('foo', 'http://localhost:3000/thing', {
  fields: [
    new Siren.Field('bar', {
      required: true, // ts(2345)
    }),
  ],
  encoding: 'UTF-16', // ts(2345)
})
```

**Comment by dillonredding** [comment]
Looks like this is also the case when accessing extensions.

```ts
action.encoding; // ERROR!
actions.fields[0].required; // ERROR!
```

I'll look into adding excess properties to the type declarations.
